### ISSUE TITLE
Generate the matrix only for the current month.

### ISSUE THREAD

**Issue by Chukuli12** [chingu-voyages/v47-tier1-team-03#28]
Description: Dynamically generating the matrix based on the current month introduces a layer of complexity, as it involves handling date-related logic and ensuring that the displayed information is relevant to the user's context.

USER STORY: "As a user, I would like the task management system to dynamically generate a matrix based on the current month.

**Comment by Chukuli12** [comment]
@florinrosoga reach out to @mickeymic25 and work with on this task.

**Comment by mickeymic25** [comment]
this was already done
