### ISSUE TITLE
Click on task name to show additional detailed description in a popup.

### ISSUE THREAD

**Issue by Chukuli12** [chingu-voyages/v47-tier1-team-03#36]
Description: Displaying additional details in a popup upon clicking is a relatively straightforward task. It enhances user experience without introducing significant complexity compared to other tasks.

USER STORY: "As a user, I want to see more details about a task when I click on it.

**Comment by Karlthetall** [comment]
https://www.figma.com/file/Z1sSZYngU1YoNi6HnfktuP/Voyage-47---Team-3?type=design&node-id=0-1&mode=design&t=dioWRidHlbZKtlB4-0

Please see the first row, 3rd screen.
